# Generated by Django 4.2.2 on 2023-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateing', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
