# Generated by Django 4.2.2 on 2023-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0003_alter_signup_password_alter_signup_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
