# Generated by Django 4.2.2 on 2023-07-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0005_passenger_rider_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Srn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='Srn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
