# Generated by Django 4.2.2 on 2023-07-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0006_map_alter_passenger_srn_alter_rider_srn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mapp', models.JSONField()),
            ],
        ),
    ]
