# Generated by Django 4.2.2 on 2023-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0007_mapval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapval',
            name='Mapp',
            field=models.DateField(),
        ),
    ]
