# Generated by Django 4.2.2 on 2023-07-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0010_alter_mapval_mapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
