# Generated by Django 4.2.2 on 2023-07-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0011_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='File',
            field=models.FileField(upload_to='downloads/'),
        ),
    ]
