# Generated by Django 4.2.2 on 2023-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0012_alter_filefield_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
