# Generated by Django 4.2.2 on 2023-07-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appthree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk1', models.CharField(max_length=200)),
            ],
        ),
    ]
